// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nylnntviddeafzbkoetd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55bG5udHZpZGRlYWZ6YmtvZXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjIxMzEsImV4cCI6MjA1ODQ5ODEzMX0.Ncmnz4LVgop41nOgKMh8E_3VWsXVpOjAGdNkHWnKeb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);